<script setup>
const series=[{title:'厨房定制',image:'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=85',to:'/products?category=厨房'},{title:'餐边收纳',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85',to:'/products?category=餐厅'},{title:'衣帽空间',image:'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=85',to:'/products?category=卧室'}]
const steps=['提交需求','上门测量','方案确认','生产安装']
</script>
<template><div class="home">
  <section class="hero"><div class="hero-copy"><h1>让空间，<br>拥有恰到好处的秩序</h1><p>以法式质感与现代工艺，定制契合生活的柜体与空间方案，<br>让每一处细节，都服务于日常的从容。</p><div class="hero-actions"><el-button type="primary" size="large" @click="$router.push('/customize')">开始定制</el-button><el-button size="large" @click="$router.push('/cases')">查看案例</el-button></div></div><div class="hero-image"></div></section>
  <div class="quick-start container"><div><small>个性化方案</small><strong class="display-title">从一张户型图开始</strong><span>上传户型或描述空间需求，快速建立定制档案。</span></div><div><el-button plain @click="$router.push('/customize')">上传户型</el-button><el-button type="primary" @click="$router.push('/customize')">描述需求</el-button></div></div>
  <section class="series container"><div class="series-heading"><h2 class="section-title">精选空间系列</h2><p>用统一的材质语言，连接不同生活场景。</p></div><router-link v-for="(item,i) in series" :key="item.title" :to="item.to" :class="['series-item',`item-${i}`]"><img :src="item.image" :alt="item.title"><h3>{{item.title}}</h3></router-link></section>
  <section class="process"><div class="container process-inner"><div><h2>从想法到落地</h2><i></i></div><div v-for="(step,i) in steps" :key="step" class="process-step"><span>0{{i+1}}</span><b>{{step}}</b></div></div></section>
</div></template>
<style scoped>
.hero{height:570px;display:grid;grid-template-columns:43% 57%;background:var(--c-bg)}.hero-copy{padding-left:max(24px,calc((100vw - 1200px)/2));display:flex;justify-content:center;align-items:flex-start;flex-direction:column}.hero-copy h1{font:500 clamp(38px,3.4vw,52px)/1.42 var(--font-display);margin:0 0 24px}.hero-copy p{color:var(--c-muted);font-size:16px;line-height:2;margin:0}.hero-actions{display:flex;gap:14px;margin-top:36px}.hero-image{background:center/cover url('../assets/images/european-kitchen-hero.png')}.quick-start{position:relative;z-index:3;margin-top:-34px;min-height:94px;padding:18px 24px 18px 30px;background:#fff;border:1px solid var(--c-border);box-shadow:var(--shadow-float);display:flex;align-items:center;justify-content:space-between}.quick-start>div:first-child{display:grid;grid-template-columns:auto 1fr;column-gap:22px}.quick-start small{grid-row:1/3;align-self:center;color:var(--c-primary);letter-spacing:.12em;border-right:1px solid var(--c-border);padding-right:22px}.quick-start strong{font-size:21px}.quick-start span{color:var(--c-muted)}.series{display:grid;grid-template-columns:230px 1.5fr 1fr 1fr;gap:20px;padding-top:72px;padding-bottom:64px;align-items:end}.series-heading{align-self:start;padding-top:24px}.series-heading p{color:var(--c-muted)}.series-heading:after{content:"";display:block;width:46px;height:1px;background:var(--c-brass);margin-top:20px}.series-item img{height:260px}.series-item.item-0 img{height:330px}.series-item h3{font:500 18px var(--font-display);margin:12px 0}.process{background:var(--c-deep);color:#f4efe7;padding:42px 0}.process-inner{display:grid;grid-template-columns:1.3fr repeat(4,1fr);align-items:center}.process h2{font:500 25px var(--font-display);margin:0}.process i{display:block;width:48px;height:1px;background:var(--c-brass);margin-top:16px}.process-step{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:18px}.process-step:not(:last-child):after{content:"";height:1px;background:rgba(165,122,74,.65);grid-column:2}.process-step span{font:400 26px var(--font-display);color:#d1a363}.process-step b{font-weight:400}
@media(max-width:900px){.hero{grid-template-columns:1fr;height:auto}.hero-copy{padding:64px 24px}.hero-image{height:420px}.series{grid-template-columns:repeat(2,1fr)}.series-heading{grid-column:1/-1}.series-item img,.series-item.item-0 img{height:260px}.process-inner{grid-template-columns:1fr 1fr;gap:28px}.process-inner>div:first-child{grid-column:1/-1}.quick-start{margin-top:0}}
@media(max-width:650px){.hero-copy p br{display:none}.hero-image{height:300px}.quick-start{align-items:flex-start;gap:18px;flex-direction:column}.quick-start>div:first-child{display:block}.quick-start small{display:block;border:0;padding:0}.quick-start strong,.quick-start span{display:block}.series{grid-template-columns:1fr;padding-top:48px}.series-item img,.series-item.item-0 img{height:260px}.process-inner{grid-template-columns:1fr}.process-inner>div:first-child{grid-column:auto}}
</style>
